spring:
  application:
    name: AXEL
  datasource:
    url: jdbc:postgresql://localhost:5432/axel_db?currentSchema=axel
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create #update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect